apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    k8s-app: stashcache
  name: stashcache-amsterdam
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: stashcache
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: stashcache
    spec:
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/stashcache
        operator: Exists
      containers:
      - env:
        - name: XC_ROOTDIR
          value: /xcache
        - name: SITENAME
          value: Amsterdam-Kubernetes-PRP
        - name: XC_RESOURCENAME
          value: Amsterdam-Kubernetes-PRP
        - name: CACHE_FQDN
          value: "fiona-r-uva.vlan7.uvalight.net"
        - name: XC_SPACE_LOW_WM
          value: '0.97'
        - name: XC_SPACE_HIGH_WM
          value: '0.99'
        image: opensciencegrid/stash-cache:stable
        ports:
         - containerPort: 1094
           hostPort: 1094
         - containerPort: 8000
           hostPort: 8000
         - containerPort: 8443
           hostPort: 8444
        imagePullPolicy: Always
        name: stashcache
        resources:
          limits:
            memory: 40Gi
            cpu: 4
          requests:
            memory: 30Gi
            cpu: 3
        volumeMounts:
        - mountPath: /etc/grid-security/hostcert.pem
          name: certificate
          readOnly: true
          subPath: hostcert.pem
        - mountPath: /etc/grid-security/hostkey.pem
          name: hostkey
          readOnly: true
          subPath: hostkey.pem
        - mountPath: /xcache
          name: datavol
      dnsPolicy: ClusterFirst
      initContainers:
      - command: ["sh", "-c", "chown -R 10940:10940 /xcache"]
        image: busybox
        imagePullPolicy: Always
        name: chowndata
        volumeMounts:
        - mountPath: /xcache
          name: datavol
      nodeSelector:
        kubernetes.io/hostname: fiona-r-uva.vlan7.uvalight.net
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certificate
        secret:
          secretName: amsterdam-certs
          items:
          - key: hostcert
            path: hostcert.pem
          defaultMode: 0600
      - name: hostkey
        secret:
          secretName: amsterdam-certs
          items:
          - key: hostkey
            path: hostkey.pem
          defaultMode: 0600
      - name: datavol
        persistentVolumeClaim:
          claimName: pvc-fiona-r-uva.vlan7.uvalight.net-0
