apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    k8s-app: stashcache
  name: stashcache-ucsd
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: stashcache
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: stashcache
    spec:
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/stashcache
        operator: Exists
      containers:
      - env:
        - name: XC_ROOTDIR
          value: /xcache
        - name: REDIRECTOR
          value: stashcache.t2.ucsd.edu:9004
        - name: SITENAME
          value: UCSD-Kubernetes-PRP
        - name: XC_RESOURCENAME
          value: UCSD-Kubernetes-PRP
        - name: CACHE_FQDN
          value: stashcache.t2.ucsd.edu
        #- name: XRDDEBUG
        #  value: "3"
        image: opensciencegrid/stash-cache:stable
        ports:
         - containerPort: 1094
           hostPort: 1094
         - containerPort: 8000
           hostPort: 8000
         - containerPort: 8443
           hostPort: 8444
        imagePullPolicy: Always
        name: stashcache
        resources:
          limits:
            cpu: "8"
            memory: 24Gi
          requests:
            cpu: "8"
            memory: 18Gi
        volumeMounts:
        - mountPath: /etc/grid-security/hostcert.pem
          name: certificate
          readOnly: true
          subPath: hostcert.pem
        - mountPath: /etc/grid-security/hostkey.pem
          name: hostkey
          readOnly: true
          subPath: hostkey.pem
        - mountPath: /xcache
          name: cachedir
        - mountPath: /xcache/data1
          name: datavol1
        - mountPath: /xcache/data2
          name: datavol2
        - mountPath: /xcache/data3
          name: datavol3
        - mountPath: /xcache/data4
          name: datavol4
        - mountPath: /xcache/data5
          name: datavol5
        - mountPath: /xcache/data6
          name: datavol6
        - mountPath: /xcache/data7
          name: datavol7
      initContainers:
      - command: ["sh", "-c", "chown -R 10940:10940 /xcache*"]
        image: busybox
        imagePullPolicy: Always
        name: chowndata
        volumeMounts:
        - mountPath: /xcache
          name: cachedir
        - mountPath: /xcache/data1
          name: datavol1
        - mountPath: /xcache/data2
          name: datavol2
        - mountPath: /xcache/data3
          name: datavol3
        - mountPath: /xcache/data4
          name: datavol4
        - mountPath: /xcache/data5
          name: datavol5
        - mountPath: /xcache/data6
          name: datavol6
        - mountPath: /xcache/data7
          name: datavol7
        resources:
          limits:
            cpu: 3
            memory: 25Gi
          requests:
            cpu: 2
            memory: 20Gi
      nodeSelector:
        kubernetes.io/hostname: stashcache.t2.ucsd.edu
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
      - name: certificate
        secret:
          secretName: ucsd-certs
          items:
          - key: hostcert
            path: hostcert.pem
          defaultMode: 0600
      - name: hostkey
        secret:
          secretName: ucsd-certs
          items:
          - key: hostkey
            path: hostkey.pem
          defaultMode: 0600
      - name: cachedir
        persistentVolumeClaim:
          claimName: pvc-osg-stashcache.t2.ucsd.edu-0
      - name: datavol1
        persistentVolumeClaim:
          claimName: pvc-osg-stashcache.t2.ucsd.edu-1
      - name: datavol2
        persistentVolumeClaim:
          claimName: pvc-osg-stashcache.t2.ucsd.edu-2
      - name: datavol3
        persistentVolumeClaim:
          claimName: pvc-osg-stashcache.t2.ucsd.edu-3
      - name: datavol4
        persistentVolumeClaim:
          claimName: pvc-osg-stashcache.t2.ucsd.edu-4
      - name: datavol5
        persistentVolumeClaim:
          claimName: pvc-osg-stashcache.t2.ucsd.edu-5
      - name: datavol6
        persistentVolumeClaim:
          claimName: pvc-osg-stashcache.t2.ucsd.edu-6
      - name: datavol7
        persistentVolumeClaim:
          claimName: pvc-osg-stashcache.t2.ucsd.edu-7

