apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    k8s-app: stashcache
  name: stashcache-ucsd
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: stashcache
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: stashcache
    spec:
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/stashcache
        operator: Exists
      containers:
      - env:
        - name: LOCAL_CACHE_DIR
          value: /xrdpfc/stash
        - name: XC_ROOTDIR
          value: /xrdpfc/stash
        - name: REDIRECTOR
          value: stashcache.t2.ucsd.edu:9004
        - name: XRD_HTTP_PORT
          value: "8000"
        - name: SITENAME
          value: UCSD-Kubernetes-PRP
        - name: XC_RESOURCENAME
          value: UCSD-Kubernetes-PRP
        - name: DATA1
          value: /data1/stash
        - name: DATA2
          value: /data2/stash
        - name: DATA3
          value: /data3/stash
        - name: DATA4
          value: /data4/stash
        - name: DATA5
          value: /data5/stash
        - name: DATA6
          value: /data6/stash
        - name: DATA7
          value: /data7/stash
        - name: CACHE_FQDN
          value: "stashcache.t2.ucsd.edu"
        image: opensciencegrid/stash-cache:stable
        ports:
         - containerPort: 8000
           hostPort: 8000
         - containerPort: 8444
           hostPort: 8444
        imagePullPolicy: Always
        name: stashcache
        resources:
          limits:
            cpu: "8"
            memory: 24Gi
          requests:
            cpu: "8"
            memory: 18Gi
        volumeMounts:
        - mountPath: /etc/grid-security/hostcert.pem
          name: certificate
          readOnly: true
          subPath: hostcert.pem
        - mountPath: /etc/grid-security/hostkey.pem
          name: hostkey
          readOnly: true
          subPath: hostkey.pem
        - mountPath: /xrdpfc/stash
          name: cachedir
        - mountPath: /data1/stash
          name: datavol1
        - mountPath: /data2/stash
          name: datavol2
        - mountPath: /data3/stash
          name: datavol3
        - mountPath: /data4/stash
          name: datavol4
        - mountPath: /data5/stash
          name: datavol5
        - mountPath: /data6/stash
          name: datavol6
        - mountPath: /data7/stash
          name: datavol7
        - mountPath: /etc/xrootd/config.d/10-k8s-https.cfg
          name: config-stash
          subPath: 10-k8s-https.cfg
        - mountPath: /etc/xrootd/config.d/40-osg-auth.cfg
          name: config-stash
          subPath: 40-osg-auth.cfg
        - mountPath: /etc/xrootd/config.d/92-disks.cfg
          name: xcachediskconfig
          subPath: 92-disks.cfg
        - mountPath: /etc/supervisord.d/90-fix-certs-initialization.conf
          name: supervisorconf
          subPath: 90-fix-certs-initialization.conf
        - mountPath: /usr/local/sbin/fix_certs.sh
          name: fixcerts
          subPath: fix_certs.sh
      initContainers:
      - command: ["sh", "-c", "chown -R 10940:10940 /data*"]
        image: busybox
        imagePullPolicy: Always
        name: chowndata
        volumeMounts:
        - mountPath: /xrdpfc/stash
          name: cachedir
        - mountPath: /data1/stash
          name: datavol1
        - mountPath: /data2/stash
          name: datavol2
        - mountPath: /data3/stash
          name: datavol3
        - mountPath: /data4/stash
          name: datavol4
        - mountPath: /data5/stash
          name: datavol5
        - mountPath: /data6/stash
          name: datavol6
        - mountPath: /data7/stash
          name: datavol7
      nodeSelector:
        kubernetes.io/hostname: stashcache.t2.ucsd.edu
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
      - name: certificate
        secret:
          secretName: ucsd-certs
          items:
          - key: hostcert
            path: hostcert.pem
          defaultMode: 0600
      - name: hostkey
        secret:
          secretName: ucsd-certs
          items:
          - key: hostkey
            path: hostkey.pem
          defaultMode: 0600
      - name: cachedir
        persistentVolumeClaim:
          claimName: pvc-osg-stashcache.t2.ucsd.edu-0
      - name: datavol1
        persistentVolumeClaim:
          claimName: pvc-osg-stashcache.t2.ucsd.edu-1
      - name: datavol2
        persistentVolumeClaim:
          claimName: pvc-osg-stashcache.t2.ucsd.edu-2
      - name: datavol3
        persistentVolumeClaim:
          claimName: pvc-osg-stashcache.t2.ucsd.edu-3
      - name: datavol4
        persistentVolumeClaim:
          claimName: pvc-osg-stashcache.t2.ucsd.edu-4
      - name: datavol5
        persistentVolumeClaim:
          claimName: pvc-osg-stashcache.t2.ucsd.edu-5
      - name: datavol6
        persistentVolumeClaim:
          claimName: pvc-osg-stashcache.t2.ucsd.edu-6
      - name: datavol7
        persistentVolumeClaim:
          claimName: pvc-osg-stashcache.t2.ucsd.edu-7
      - configMap:
          defaultMode: 420
          name: stashcache.d
        name: config-stash
      - configMap:
          defaultMode: 420
          name: supervisor.d
        name: supervisorconf
      - configMap:
          defaultMode: 484
          name: fixcerts
        name: fixcerts
      - configMap:
          defaultMode: 420
          name: mdisks.cfg
        name: xcachediskconfig
