apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    k8s-app: stashcache
  name: stashcache-amsterdam
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  selector:
    matchLabels:
      k8s-app: stashcache
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: stashcache
    spec:
      containers:
      - env:
        - name: LOCAL_CACHE_DIR
          value: /data/stash
        - name: XC_ROOTDIR
          value: /data/stash
        - name: SITENAME
          value: Amsterdam-Kubernetes-PRP
        - name: XC_RESOURCENAME
          value: Amsterdam-Kubernetes-PRP
        image: opensciencegrid/stash-cache:stable
        imagePullPolicy: Always
        name: stashcache
        resources:
          limits:
            memory: 40Gi
            cpu: 4
          requests:
            memory: 30Gi
            cpu: 3
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/grid-security/hostcert.pem
          name: hostcert
        - mountPath: /etc/grid-security/hostkey.pem
          name: hostkey
        - mountPath: /etc/xrootd/config.d/10-k8s-https.cfg
          name: config
          subPath: 10-k8s-https.cfg
        - mountPath: /etc/supervisord.d/90-fix-certs-initialization.conf
          name: supervisorconf
          subPath: 90-fix-certs-initialization.conf
        - mountPath: /usr/local/sbin/fix_certs.sh
          name: fixcerts
          subPath: fix_certs.sh
        - mountPath: /data/stash
          name: datavol
      dnsPolicy: ClusterFirst
      hostNetwork: true
      initContainers:
      - command: ["sh", "-c", "chown -R 10940:10940 /data/stash"]
        image: busybox
        imagePullPolicy: Always
        name: chowndata
        volumeMounts:
        - mountPath: /data/stash
          name: datavol
      nodeSelector:
        kubernetes.io/hostname: fiona-r-uva.vlan7.uvalight.net
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /etc/grid-security/hostcert.pem
          type: File
        name: hostcert
      - hostPath:
          path: /etc/grid-security/hostkey.pem
          type: File
        name: hostkey
      - configMap:
          defaultMode: 420
          name: stashcache.d
        name: config
      - configMap:
          defaultMode: 420
          name: supervisor.d
        name: supervisorconf
      - configMap:
          defaultMode: 484
          name: fixcerts
        name: fixcerts
      - hostPath:
          path: /data
          type: Directory
        name: datavol

