apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: stashcache
  name: stashcache-amsterdam
  namespace: osg
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: stashcache
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: fiona-r-uva.vlan7.uvalight.net
      initContainers:
      - name: chowndata
        image: busybox
        command: ["sh", "-c", "chown -R 10940:10940 /data/stash"]
        volumeMounts:
        - name: datavol
          mountPath: /data/stash
      containers:
      - name: stashcache
        resources:
           limits:
              memory: 40Gi
           requests:
              memory: 30Gi
        image: opensciencegrid/stash-cache:development
        #command: ["sh", "-c", "sleep infinity"]
        env:
        - name: LOCAL_CACHE_DIR
          value: /data/stash
        - name: XC_ROOTDIR
          value: /data/stash
        - name: SITENAME
          value: Amsterdam-Kubernetes-PRP
        - name: XC_RESOURCENAME
          value: Amsterdam-Kubernetes-PRP
        imagePullPolicy: Always
        volumeMounts:
        - name: hostcert
          mountPath: /etc/grid-security/hostcert.pem
        - name: hostkey
          mountPath: /etc/grid-security/hostkey.pem
        - name: config
          mountPath: /etc/xrootd/config.d/95-k8s-ports.cfg
          subPath: 95-k8s-ports.cfg
        - name: supervisorconf
          mountPath: /etc/supervisord.d/90-fix-certs-initialization.conf
          subPath: 90-fix-certs-initialization.conf
        - name: fixcerts
          mountPath: /usr/local/sbin/fix_certs.sh
          subPath: fix_certs.sh
        - name: datavol
          mountPath: /data/stash
      volumes:
      - name : hostcert
        hostPath:
           path: /etc/grid-security/hostcert.pem
           type: File
      - name : hostkey
        hostPath:
           path: /etc/grid-security/hostkey.pem
           type: File
      - name: config
        configMap:
          name: stashcache.d
      - name: supervisorconf
        configMap:
          name: supervisor.d
      - name: fixcerts
        configMap:
          name: fixcerts
          defaultMode: 0744
      - name: datavol
        hostPath:
          path: /data
          type: Directory
