apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: stashcache
  name: stashcache-ucsd
  namespace: osg
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: stashcache
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: stashcache.t2.ucsd.edu
      initContainers:
      - name: chowndata
        image: busybox
        command: ["sh", "-c", "chown -R 999:997 /data* /xrdpfc/stash"]
        volumeMounts:
        - name: cachedir
          mountPath: /xrdpfc/stash
        - name: datavol1
          mountPath: /data1/stash
        - name: datavol2
          mountPath: /data2/stash
        - name: datavol3
          mountPath: /data3/stash
        - name: datavol4
          mountPath: /data4/stash 
        - name: datavol5
          mountPath: /data5/stash
        - name: datavol6
          mountPath: /data6/stash
        - name: datavol7
          mountPath: /data7/stash
      containers:
      - name: stashcache
        resources:
           limits:
              memory: 24Gi
           requests:
              memory: 18Gi
        image: opensciencegrid/prp-stashcache
        #command: ["sh", "-c", "sleep infinity"]
        env:
        - name: LOCAL_CACHE_DIR
          value: /xrdpfc/stash
        - name: REDIRECTOR
          value: stashcache.t2.ucsd.edu:9004
        - name: XRDHTTPPORT
          value: "9001"
        - name: SITENAME
          value: UCSD-Kubernetes-PRP
        - name: DATA1
          value: /data1/stash
        - name: DATA2
          value: /data2/stash
        - name: DATA3
          value: /data3/stash
        - name: DATA4
          value: /data4/stash
        - name: DATA5
          value: /data5/stash
        - name: DATA6
          value: /data6/stash
        - name: DATA7
          value: /data7/stash
        imagePullPolicy: Always
        volumeMounts:
        - name: hostcert
          mountPath: /etc/grid-security/hostcert.pem
        - name: hostkey
          mountPath: /etc/grid-security/hostkey.pem
        - name: cachedir
          mountPath: /xrdpfc/stash
        - name: config
          mountPath: /etc/xrootd
        - name: datavol1
          mountPath: /data1/stash
        - name: datavol2
          mountPath: /data2/stash
        - name: datavol3
          mountPath: /data3/stash
        - name: datavol4
          mountPath: /data4/stash  
        - name: datavol5
          mountPath: /data5/stash
        - name: datavol6
          mountPath: /data6/stash
        - name: datavol7
          mountPath: /data7/stash
      volumes:
      - name : hostcert
        hostPath:
           path: /etc/grid-security/hostcert.pem
           type: File
      - name : hostkey
        hostPath:
           path: /etc/grid-security/hostkey.pem
           type: File
      - name: config
        configMap:
          name: stashcache
      - name: cachedir
        hostPath:
          path: /nvme0
          type: Directory
      - name: datavol1
        hostPath:
          path: /data1
          type: Directory
      - name: datavol2
        hostPath:
          path: /data2
          type: Directory
      - name: datavol3
        hostPath:
          path: /data3
          type: Directory
      - name: datavol4
        hostPath:
          path: /data4
          type: Directory
      - name: datavol5
        hostPath:
          path: /data5
          type: Directory
      - name: datavol6
        hostPath:
          path: /data6
          type: Directory
      - name: datavol7
        hostPath:
          path: /data7
          type: Directory