apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    k8s-app: stashcache
  name: stashcache-kisti
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: stashcache
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: stashcache
    spec:
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/stashcache
        operator: Exists
      containers:
      - env:
        - name: XC_ROOTDIR
          value: /xcache
        - name: SITENAME
          value: Kisti-Kubernetes-PRP
        - name: XC_RESOURCENAME
          value: Kisti-Kubernetes-PRP
        - name: CACHE_FQDN
          value: "dtn2-daejeon.kreonet.net"
        image: opensciencegrid/stash-cache:fresh
        ports:
         - containerPort: 1094
           hostPort: 1094
         - containerPort: 8000
           hostPort: 8000
         - containerPort: 8443
           hostPort: 8444
        imagePullPolicy: Always
        name: stashcache
        resources:
          limits:
            memory: 20Gi
            cpu: 4
          requests:
            memory: 10Gi
            cpu: 3
        volumeMounts:
        - mountPath: /etc/grid-security/hostcert.pem
          name: certificate
          readOnly: true
          subPath: hostcert.pem
        - mountPath: /etc/grid-security/hostkey.pem
          name: hostkey
          readOnly: true
          subPath: hostkey.pem
        - mountPath: /xcache
          name: dataroot
        - mountPath: /data1/stash
          name: dataroot
        - mountPath: /data2/stash
          name: dataroot2
        - mountPath: /data3/stash
          name: dataroot3
      dnsPolicy: ClusterFirst
      initContainers:
      - command: ["sh", "-c", "chown -R 10940:10940 /xcache*"]
        image: busybox
        imagePullPolicy: Always
        name: chowndata
        volumeMounts:
        - mountPath: /xcache
          name: dataroot
        - mountPath: /xcache/data1
          name: dataroot
        - mountPath: /xcache/data2
          name: dataroot2
        - mountPath: /xcache/data3
          name: dataroot3
      nodeSelector:
        kubernetes.io/hostname: dtn2-daejeon.kreonet.net
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certificate
        secret:
          secretName: kisti-certs
          items:
          - key: hostcert
            path: hostcert.pem
          defaultMode: 0600
      - name: hostkey
        secret:
          secretName: kisti-certs
          items:
          - key: hostkey
            path: hostkey.pem
          defaultMode: 0600
      - name: dataroot
        persistentVolumeClaim:
          claimName: pvc-dtn2-daejeon-kreonet-net-1
      - name: dataroot2
        persistentVolumeClaim:
          claimName: pvc-dtn2-daejeon-kreonet-net-2
      - name: dataroot3
        persistentVolumeClaim:
          claimName: pvc-dtn2-daejeon-kreonet-net-3
