apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    k8s-app: stashcache
  name: stashcache-greatplains
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: stashcache
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: stashcache
    spec:
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/stashcache
        operator: Exists
      containers:
      - env:
        - name: LOCAL_CACHE_DIR
          value: /data/stash
        - name: XC_ROOTDIR
          value: /data/stash
        - name: SITENAME
          value: GreatPLains-Kubernetes-PRP
        - name: RAMSIZE
          value: 30g
        - name: REDIRECTOR
          value: osg.kans.nrp.internet2.edu:9004
        - name: XRDHTTPPORT
          value: "8000"
        - name: CACHE_FQDN
          value: "osg.kans.nrp.internet2.edu"
        - name: XC_SPACE_LOW_WM
          value: '0.93'
        - name: XC_SPACE_HIGH_WM
          value: '0.95'
        image: opensciencegrid/stash-cache:stable
        imagePullPolicy: Always
        name: stashcache
        ports:
         - containerPort: 8000
           hostPort: 8000
         - containerPort: 8444
           hostPort: 8444
        resources:
          limits:
            cpu: 4
            memory: 44Gi
          requests:
            cpu: 3
            memory: 42Gi
        volumeMounts:
        - mountPath: /etc/grid-security/hostcert.pem
          name: certificate
          readOnly: true
          subPath: hostcert.pem
        - mountPath: /etc/grid-security/hostkey.pem
          name: hostkey
          readOnly: true
          subPath: hostkey.pem
        - mountPath: /etc/xrootd/config.d/10-k8s-https.cfg
          name: config-http
          subPath: 10-k8s-https.cfg
        - mountPath: /etc/supervisord.d/90-fix-certs-initialization.conf
          name: supervisorconf
          subPath: 90-fix-certs-initialization.conf
        - mountPath: /usr/local/sbin/fix_certs.sh
          name: fixcerts
          subPath: fix_certs.sh
        - mountPath: /data/stash
          name: datavol
      dnsPolicy: ClusterFirst
      initContainers:
      - command: ["sh", "-c", "chown -R 10940:10940 /data*"]
        image: busybox
        imagePullPolicy: Always
        name: chowndata
        volumeMounts:
        - mountPath: /data/stash
          name: datavol
      nodeSelector:
        kubernetes.io/hostname: osg.kans.nrp.internet2.edu
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certificate
        secret:
          secretName: kansascity-certs
          items:
          - key: hostcert
            path: hostcert.pem
          defaultMode: 0600
      - name: hostkey
        secret:
          secretName: kansascity-certs
          items:
          - key: hostkey
            path: hostkey.pem
          defaultMode: 0600
      - configMap:
          defaultMode: 420
          name: stashcache.d
        name: config-http
      - configMap:
          defaultMode: 420
          name: supervisor.d
        name: supervisorconf
      - configMap:
          defaultMode: 484
          name: fixcerts
        name: fixcerts
      - name: datavol
        persistentVolumeClaim:
          claimName: pvc-osg.kans.nrp.internet2.edu-1
