apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    k8s-app: stashcache
  name: stashcache-kisti
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: stashcache
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: stashcache
    spec:
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/stashcache
        operator: Exists
      containers:
      - env:
        - name: LOCAL_CACHE_DIR
          value: /data/stash
        - name: XC_ROOTDIR
          value: /data/stash
        - name: SITENAME
          value: Kisti-Kubernetes-PRP
        - name: XC_RESOURCENAME
          value: Kisti-Kubernetes-PRP
        - name: DATA1
          value: /data1/stash
        - name: DATA2
          value: /data2/stash
        - name: DATA3
          value: /data3/stash
        - name: CACHE_FQDN
          value: "dtn2-daejeon.kreonet.net"
        image: opensciencegrid/stash-cache:stable
        ports:
         - containerPort: 8000
           hostPort: 8000
         - containerPort: 8444
           hostPort: 8444
        imagePullPolicy: Always
        name: stashcache
        resources:
          limits:
            memory: 20Gi
            cpu: 4
          requests:
            memory: 10Gi
            cpu: 3
        volumeMounts:
        - mountPath: /etc/grid-security/hostcert.pem
          name: certificate
          readOnly: true
          subPath: hostcert.pem
        - mountPath: /etc/grid-security/hostkey.pem
          name: hostkey
          readOnly: true
          subPath: hostkey.pem
        - mountPath: /etc/xrootd/config.d/10-k8s-https.cfg
          name: config
          subPath: 10-k8s-https.cfg
        - mountPath: /etc/xrootd/config.d/92-disks.cfg
          name: configdisk
          subPath: 92-disks.cfg
        - mountPath: /data/stash
          name: dataroot
        - mountPath: /data1/stash
          name: dataroot
        - mountPath: /data2/stash
          name: dataroot2
        - mountPath: /data3/stash
          name: dataroot3
      dnsPolicy: ClusterFirst
      initContainers:
      - command: ["sh", "-c", "chown -R 10940:10940 /data*"]
        image: busybox
        imagePullPolicy: Always
        name: chowndata
        volumeMounts:
        - mountPath: /data/stash
          name: dataroot
        - mountPath: /data1/stash
          name: dataroot
        - mountPath: /data2/stash
          name: dataroot2
        - mountPath: /data3/stash
          name: dataroot3
      nodeSelector:
        kubernetes.io/hostname: dtn2-daejeon.kreonet.net
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certificate
        secret:
          secretName: kisti-certs
          items:
          - key: hostcert
            path: hostcert.pem
          defaultMode: 0600
      - name: hostkey
        secret:
          secretName: kisti-certs
          items:
          - key: hostkey
            path: hostkey.pem
          defaultMode: 0600
      - configMap:
          defaultMode: 420
          name: stashcache.d
        name: config
      - configMap:
          defaultMode: 420
          name: mdisks.cfg
        name: configdisk
      - configMap:
          defaultMode: 420
          name: supervisor.d
        name: supervisorconf
      - name: dataroot
        persistentVolumeClaim:
          claimName: pvc-dtn2-daejeon-kreonet-net-1
      - name: dataroot2
        persistentVolumeClaim:
          claimName: pvc-dtn2-daejeon-kreonet-net-2
      - name: dataroot3
        persistentVolumeClaim:
          claimName: pvc-dtn2-daejeon-kreonet-net-3
