apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    k8s-app: stashcache
  name: stashcache-greatplains
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: stashcache
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: stashcache
    spec:
      containers:
      - env:
        - name: LOCAL_CACHE_DIR
          value: /data/stash
        - name: SITENAME
          value: GreatPLains-Kubernetes-PRP
        - name: RAMSIZE
          value: 30g
        - name: REDIRECTOR
          value: osg.kans.nrp.internet2.edu:9004
        - name: XRDHTTPPORT
          value: "9001"
        image: efajardo/prp-stashcache
        imagePullPolicy: Always
        name: stashcache
        resources:
          limits:
            cpu: 4
            memory: 44Gi
          requests:
            cpu: 3
            memory: 42Gi
        volumeMounts:
        - mountPath: /etc/grid-security/hostcert.pem
          name: hostcert
        - mountPath: /etc/grid-security/hostkey.pem
          name: hostkey
        - mountPath: /etc/xrootd
          name: config
        - mountPath: /data/stash
          name: datavol
      dnsPolicy: ClusterFirst
      hostNetwork: true
      initContainers:
      - command: ["sh", "-c", "chown -R 999:997 /data*"]
        image: busybox
        imagePullPolicy: Always
        name: chowndata
        volumeMounts:
        - mountPath: /data/stash
          name: datavol
      nodeSelector:
        kubernetes.io/hostname: osg.kans.nrp.internet2.edu
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /etc/grid-security/hostcert.pem
          type: File
        name: hostcert
      - hostPath:
          path: /etc/grid-security/hostkey.pem
          type: File
        name: hostkey
      - configMap:
          defaultMode: 420
          name: stashcache
        name: config
      - hostPath:
          path: /tank
          type: Directory
        name: datavol

